import os
import sys

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from langchain_core.messages import HumanMessage, AIMessage, SystemMessage
from utils.llm_pick import pick_llm
from models.schema import DataAgentState, RouterSchema
from graphs.sql_agent_graph import sql_analyst
from graphs.etl_agent_graph import etl_analyst

llm = pick_llm("low")
llm_router = llm.with_structured_output(RouterSchema)

ROUTER_SYSTEM_PROMPT = (
    "You are an expert request router in an enterprise Data AI assistant.\n"
    "Classify the user's intent into either:\n"
    "- 'sql': Queries requesting database information, table counts, schema queries, users, rides, payments, ratings, etc.\n"
    "- 'etl': Tasks requesting data extraction from REST APIs, web scraping, data transformations with Pandas, or saving files (CSV, JSON, Parquet).\n"
    "Classify accurately."
)


def router_node(state: DataAgentState) -> dict:
    """
    Evaluates the conversation history and classifies the request as either 'sql' or 'etl'.
    """
    messages = state.get("messages", [])
    if not messages:
        raise ValueError("DataAgentState must have at least one message.")

    last_message = messages[-1]
    user_query = last_message.content if hasattr(last_message, "content") else str(last_message)

    router_res = llm_router.invoke([
        SystemMessage(content=ROUTER_SYSTEM_PROMPT),
        HumanMessage(content=user_query)
    ])

    return {"route_response": router_res.answer}


def sql_node(state: DataAgentState) -> dict:
    """
    Delegates the user's database inquiry to the SQL Analyst subgraph.
    Returns the resulting AIMessage to update the supervisor's message history.
    """
    messages = state.get("messages", [])
    last_message = messages[-1]
    user_query = last_message.content if hasattr(last_message, "content") else str(last_message)

    sql_result = sql_analyst.invoke({
        "messages": [HumanMessage(content=user_query)],
        "user_message": user_query
    })

    # Find the final AIMessage generated by the SQL analyst
    sql_messages = sql_result.get("messages", [])
    for msg in reversed(sql_messages):
        if isinstance(msg, AIMessage) and msg.content:
            return {"messages": [msg]}

    final_answer = sql_result.get("final_answer", "SQL analysis completed.")
    return {"messages": [AIMessage(content=str(final_answer))]}


def etl_node(state: DataAgentState) -> dict:
    """
    Delegates the user's data extraction/transformation task to the ETL Analyst subgraph.
    Returns the resulting final AIMessage to update the supervisor's message history.
    """
    messages = state.get("messages", [])

    etl_result = etl_analyst.invoke({"messages": messages})

    # Retrieve the final user-facing AIMessage from the ETL execution history
    etl_messages = etl_result.get("messages", [])
    for msg in reversed(etl_messages):
        if isinstance(msg, AIMessage) and msg.content and not getattr(msg, "tool_calls", None):
            return {"messages": [msg]}

    if etl_messages:
        last = etl_messages[-1]
        content = last.content if hasattr(last, "content") else str(last)
        return {"messages": [AIMessage(content=content)]}

    return {"messages": [AIMessage(content="ETL process completed.")]}